# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0ec401f128cb009fe02db578899ed44ce5ebeb30715c03b988fe10531357a0b84c3afc2e1668d027dfabd98b9c6c66f5a481b9f2eb9a9f483bf40ad4ece51cf

test:
  secret_key_base: aaea00676ec1e0f1cd49b9b00abd1759a5254d95cbbd6c839ae0db396fc57dbb6998ab6fa4865678081d716659bb04ce56b7df1d666c1637d4700f3a5a7784c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
